### ISSUE TITLE
App is a bit sluggish

### ISSUE THREAD

**Issue by savvasdalkitsis** [digitalbuddha/Ebony#6]
There seems to be a lot of overdrawn areas and the drawing performance graph while scrolling frequently goes over the threshold for smooth rendering as seen in the screenshots ![Screenshot_20230305-110735.png](https://user-images.githubusercontent.com/873077/222956940-8254b079-406c-4184-a393-7e1ced8c6794.png)

![Screenshot_20230305-110619.png](https://user-images.githubusercontent.com/873077/222956941-fc4b3f2d-ae00-4716-8ca4-6bf61f15a012.png)

**Comment by digitalbuddha** [comment]
I was being lazy with alpha. I'll make proper composite colors today.
Thanks for reporting

**Comment by savvasdalkitsis** [comment]
I believe the latest build removed the activity background altogether causing the app to render whatever is underneath it :D 

I can see my animated wallpaper under the app content

**Comment by digitalbuddha** [comment]
ha yea fixing now :-D

**Comment by digitalbuddha** [comment]
All set could you check again please?

**Comment by savvasdalkitsis** [comment]
The background is back now :)

The app is faster, less overdraw for sure.

There still seems to be a weird view drawing under the main content scrolling in the opposite direction of the feed though.

It's not affecting performance though so you can close this. Attaching a video of the weird view in question:

https://user-images.githubusercontent.com/873077/222965208-3a8ec4e7-edf2-4dd6-a237-f45720650c81.mp4

**Comment by digitalbuddha** [comment]
Yeah I noticed that too and wasn't sure what it is. I'll go diving at some point to find it. Closing for now
